server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: tsy7172139
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 18000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制日志输出
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mapper/*.xml

jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT加解密使用的秘钥
  secretKey: yeb-secret
  #JWT过期时间
  expiration: 604800
  #JWT负载中拿到开头
  tokenHead: Bearer